import json, shutil, os

class MetaToRes:
    def __init__(self, json_data):
        """
        Inisialisasi MetaToRes dengan data JSON.
        :param json_data: Data JSON yang berisi definisi tabel.
        """
        if isinstance(json_data, str):
            self.json_data = json.loads(json_data)
        elif isinstance(json_data, dict):  # Sesuaikan jika data berupa list
            self.json_data = json_data
        else:
            raise ValueError("Input harus berupa string JSON atau list dictionary.")
    

    def ubah_nama(self,input_text):
        """
        Mengubah teks dengan format snake_case menjadi PascalCase.
        Contoh:
        - "jenis_barang" -> "JenisBarang"
        """
        if not input_text:
            return ""
        # Pecah teks berdasarkan underscore (_), kapitalisasi setiap kata, lalu gabungkan
        if(input_text.lower() == 'users'):
            return "User" + "Resource"
        return ''.join(word.capitalize() for word in input_text.split('_')) + "Resource"
    
    def get_class_rel_dir(self, table_data, table_name):
        for i in table_data:
            if(i['table'] == table_name):
                return "App\Http\Resources\\" + ( i['dir'] + "\\" ) if i['dir'] else "App\Http\Resources\\"
        return "App\Http\Resources\\"
    

    def json_to_model(self, table_data, refs_data):
        dir        = ( '\\' + table_data["dir"] ).replace('/','\\') if table_data["dir"] else ""
        table_name = table_data["table"]
        columns    = table_data["items"]
        model_name = self.ubah_nama(table_name)
 
        #-------------------------------------------------
        mod = '<?php \n'
        mod+= f'//Generated by ArindyProject -> https://github.com/arindyproject/dbdiagram2laravel \n'
        mod+= f'namespace App\Http\Resources{dir}; \n'
        mod+= f'use Illuminate\Http\Request; \n'
        mod+= f'use Illuminate\Http\Resources\Json\JsonResource; \n\n'
        #-------------------------------------------------
        mod+= 'Class ' + model_name+ ' extends JsonResource { \n'
        mod+= '    /**\n'
        mod+= '    * Transform the resource into an array.\n'
        mod+= '    *\n'
        mod+= '    * @return array<string, mixed>\n'
        mod+= '    */\n'
        #-------------------------------------------------
        mod+= '    public function toArray($request){\n'
        mod+= '        return[\n'
        #-------------------------------------------------
        
        #-------------------------------------------------
        max_length = max(len(i['name']) for i in columns)
        for i in columns:
            mod += f'            "{i["name"]}"{" " * (max_length - len(i["name"]))} => $this->{i["name"]}, \n'
        #-------------------------------------------------

        #-------------------------------------------------
        mod+= '        ]; \n'
        mod+= '    } \n'
        #-------------------------------------------------
        mod+= '} \n'
        #-------------------------------------------------
        return {
            'table' : table_name,
            'model' : model_name,
            'path'  : '/' + table_data["dir"] if table_data["dir"] else '',
            'class' : mod
        }
    
    def process_and_save(self):
        # Path ke direktori yang akan dihapus
        models_dir = "out/app/Resources"

        # Hapus direktori jika ada
        if os.path.exists(models_dir):
            shutil.rmtree(models_dir)
            print(f"Direktori {models_dir} berhasil dihapus.")

        table_data = self.json_data['tabels']
        refs_data = self.json_data['refs']

        for i in table_data:
            d = self.json_to_model(i, refs_data)
            output_dir = models_dir + d['path']
            
            # Membuat folder jika belum ada
            os.makedirs(output_dir, exist_ok=True)
            
            # Path untuk file model
            output_path = output_dir + "/" + d['model'] + '.php'
            
            # Menulis file model
            with open(output_path, "w") as file:
                file.write(d['class'])

            print(f"Resources berhasil disimpan di {output_path}")
            print(d['class'])
            #print(json.dumps(d, indent=4))